FROM nvidia/cuda:10.1-devel-ubuntu18.04

RUN apt-get update 
RUN apt-get install -y python3 python3-dev python3-pip

COPY requirements.txt /

RUN pip3 install -r /requirements.txt
RUN python3 -c "import nltk; nltk.download('punkt')"
RUN python3 -c "import nltk; nltk.download('words')"

WORKDIR /root

RUN mkdir trained data

COPY train_we.py .
COPY config.cuda.yaml .


